### ISSUE TITLE
TurtleTurtle.org public nodes status

### ISSUE THREAD

**Issue by mrrovot** [brandonlehmann/turtlecoin-api-proxy#1]
Hi Brandon,

Used your public api and code to maybe create a turtleturtle.org/status of all public nodes, right now I could only find your turtlenode.io nodes but in the near future I assume there will be more public nodes

http://trtlnodes.surge.sh/  

is it ok to use it?

**Comment by brandonlehmann** [comment]
Feel free to hit my api proxy, I have no problem with that at all. I would; however, make it clear that with the recent updates as shown on the main turtlenode site that using the individual nodes is no longer supported (my origin for the API proxy and the LBs are the only thing allowed to hit those directly for wallet use) and must be used through the regional load balancers or the public round robin.

**Comment by mrrovot** [comment]
if I understood correctly then only those are the valid nodes ppl can use?
    public.turtlenode.io
    us-west.turtlenode.io
    us-east.turtlenode.io
    europe.turtlenode.io
    asia.turtlenode.io

**Comment by brandonlehmann** [comment]
That’s an option. Depends on why you’re listing them. 

If you’re listing them for informational purpose you can list all without a problem. 

If you’re listing for people to use them with wallets, I’d list the LBs and public only.

I’d hate for people to think that they can connect to each node when they can’t. That’s part of the reason I don’t show the actual hostnames on the main turtlenode page :)

Does that help?

**Comment by mrrovot** [comment]
yep, I think it will be mostly for info, ppl that want to connect/have problem can go to turtlenode.io and find out more info, I will link to turtlenode site from the table
